services:
  frontend:
    build:
      context: ./frontend/jobflow-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/jobflow-ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/jobflow-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/jobflow-api:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    depends_on:
      - db
    env_file:
      - ./backend/jobflow-api/.env

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/jobflow-api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
