services:
  frontend:
    build:
      context: ./frontend/jobflow-ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/jobflow-ui:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/jobflow-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/jobflow-api:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - SPRING_DATA_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      - db
      - elasticsearch
    env_file:
      - ./backend/jobflow-api/.env

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/jobflow-api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch-jobflow
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana-jobflow
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
volumes:
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local
  frontend_node_modules:
    driver: local